// Generated by scripts/compute-cloud-worker-fingerprint.mjs — do not edit.
export const EMBEDDED_CLOUD_WORKER_BUNDLE_FINGERPRINT: string | undefined = "sha256:65841e7919ad7cd973f3e07edd60247199272cb6b9577a74ef3703c1cb181beb";
